'use client';

import Link from 'next/link';
import { useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle2, HelpCircle, Mail, RefreshCw, ShieldCheck } from 'lucide-react';

export default function PaymentOutcome({ invoiceId, state }: { invoiceId: string; state: 'success' | 'failed' | 'cancelled' | 'dispute' | 'already-paid' }) {
  const [sent, setSent] = useState(false);
  const copy = {
    success: { eyebrow: 'Payment complete', title: 'Thanks, your payment is on its way.', text: 'A receipt for invoice INV-1048 will be sent to your email shortly.', Icon: CheckCircle2, color: 'text-emerald-600', button: 'Return home' },
    failed: { eyebrow: 'Payment could not be completed', title: 'Let’s try that again.', text: 'Your card was not charged. Check your details or use another payment method.', Icon: AlertCircle, color: 'text-amber-600', button: 'Try payment again' },
    cancelled: { eyebrow: 'Payment cancelled', title: 'No payment was taken.', text: 'Your invoice is still open whenever you are ready to complete payment.', Icon: RefreshCw, color: 'text-brand-blue', button: 'Return to payment' },
    dispute: { eyebrow: 'Contact the sender', title: 'Tell us what happened.', text: 'Share a note and the invoice owner will follow up with you directly.', Icon: HelpCircle, color: 'text-brand-blue', button: 'Send message' },
    'already-paid': { eyebrow: 'Already paid?', title: 'We can help reconcile this invoice.', text: 'Send the payment details and the invoice owner will verify your payment.', Icon: CheckCircle2, color: 'text-emerald-600', button: 'Send payment details' },
  }[state];
  const isForm = state === 'dispute' || state === 'already-paid';
  return <main className="min-h-screen bg-gray-50 px-4 py-8 text-gray-900 sm:px-6"><div className="mx-auto max-w-xl"><Link href={`/pay/${invoiceId}`} className="inline-flex items-center gap-2 text-sm font-bold text-gray-500 hover:text-gray-900"><ArrowLeft className="h-4 w-4" /> Back to invoice</Link><section className="mt-12 rounded-3xl border border-gray-200 bg-white p-7 text-center shadow-apple sm:p-10"><div className="mx-auto flex size-16 items-center justify-center rounded-2xl bg-gray-50"><copy.Icon className={`size-8 ${copy.color}`} /></div><p className="mt-6 text-xs font-bold uppercase tracking-widest text-brand-blue">{copy.eyebrow}</p><h1 className="mt-3 font-heading text-3xl font-bold tracking-tight">{copy.title}</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-gray-500">{copy.text}</p>{isForm && <div className="mt-7 text-left"><label className="text-xs font-bold text-gray-600">{state === 'dispute' ? 'Message' : 'Payment reference'}<textarea className="mt-2 min-h-28 w-full resize-none rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" placeholder={state === 'dispute' ? 'Tell the sender what you need help with...' : 'Transaction ID, date, or any useful detail'} /></label></div>}{sent ? <div className="mt-7 rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-700">Message sent. The invoice owner will be in touch.</div> : <button onClick={() => isForm ? setSent(true) : undefined} className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand-blue px-5 py-3.5 text-sm font-bold text-white hover:bg-brand-blue/90">{isForm && <Mail className="h-4 w-4" />}{state === 'success' ? <Link href="/" className="w-full">{copy.button}</Link> : state === 'failed' || state === 'cancelled' ? <Link href={`/pay/${invoiceId}`} className="w-full">{copy.button}</Link> : copy.button}</button>}<div className="mt-6 flex items-center justify-center gap-2 text-xs text-gray-400"><ShieldCheck className="h-4 w-4 text-emerald-500" /> Secure invoice portal</div></section></div></main>;
}
