'use client';
import { useState } from 'react';
import { CheckCircle2, ShieldCheck, ArrowLeft, CreditCard, AlertCircle } from 'lucide-react';
import Link from 'next/link';
export default function PaymentPortal() {
  const [paid, setPaid] = useState(false);
  const [help, setHelp] = useState(false);
  if (paid) return <main className="min-h-screen bg-gray-50 flex items-center justify-center p-6"><div className="w-full max-w-md rounded-3xl border border-gray-200 bg-white p-8 text-center shadow-apple"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-500"/><h1 className="mt-5 font-heading text-2xl font-bold text-gray-900">Payment received</h1><p className="mt-2 text-sm leading-6 text-gray-500">Your payment for INV-1048 has been recorded and a receipt is on its way.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-brand-blue px-5 py-3 text-sm font-bold text-white">Return home</Link></div></main>;
  return <main className="min-h-screen bg-gray-50 p-6"><div className="mx-auto max-w-5xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-gray-500"><ArrowLeft className="h-4 w-4"/> Astrix</Link><div className="mx-auto mt-12 grid max-w-4xl gap-6 md:grid-cols-[1fr_0.8fr]"><section className="rounded-3xl border border-gray-200 bg-white p-8 shadow-apple"><p className="text-xs font-bold uppercase tracking-widest text-brand-blue">Invoice payment</p><h1 className="mt-3 font-heading text-3xl font-bold text-gray-900">INV-1048</h1><p className="mt-2 text-sm text-gray-500">Northstar Studio · Payment due</p><div className="mt-10 border-y border-gray-100 py-6"><p className="text-sm text-gray-500">Amount due</p><p className="mt-1 font-heading text-4xl font-bold text-gray-900">$8,400.00</p></div><div className="mt-6 flex items-center gap-3 text-sm text-gray-600"><ShieldCheck className="h-5 w-5 text-emerald-500"/> Secure payment powered by Astrix</div></section><section className="rounded-3xl border border-gray-200 bg-white p-8 shadow-apple"><h2 className="font-heading text-xl font-bold text-gray-900">Complete payment</h2><label className="mt-6 block text-xs font-bold text-gray-600">Card number<input className="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" placeholder="4242 4242 4242 4242"/></label><div className="mt-4 grid grid-cols-2 gap-3"><input className="rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" placeholder="MM / YY"/><input className="rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm outline-none focus:border-brand-blue" placeholder="CVC"/></div><button onClick={() => setPaid(true)} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-brand-blue px-4 py-3.5 text-sm font-bold text-white"><CreditCard className="h-4 w-4"/> Pay $8,400.00</button><button onClick={() => setHelp(true)} className="mt-3 w-full text-xs font-bold text-gray-500">I already paid / need help</button>{help && <p className="mt-4 flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-xs font-medium text-amber-700"><AlertCircle className="h-4 w-4"/> Contact the sender to resolve this invoice.</p>}</section></div></div></main>;
}
